apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    owner: Misyuro
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      owner: Misyuro
  template:
    metadata:
      labels:
        app: nginx
        owner: Misyuro
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
